// Generated by CoffeeScript 1.7.1
(function() {
  var Enterprise, application, controller, controller2;

  Enterprise = require("../../../src/lib");

  application = new Enterprise.Application();

  controller = new Enterprise.Controller();

  controller.get("/items", function(req, res, next) {
    return res.json({
      a: "testeDoido"
    });
  });

  controller2 = new Enterprise.Controller();

  controller2.get("/testeDoido2", function(req, res, next) {
    return res.json({
      a: "testeDoido22222"
    });
  });

  application.register(controller);

  application.register(controller2);

  module.exports = application;

}).call(this);

//# sourceMappingURL=index.map
