// Generated by CoffeeScript 1.7.1
(function() {
  var AppRouter, Gallery;

  Gallery = require('./lib/gallery');

  AppRouter = (function() {
    function AppRouter(router) {
      this.router = router;
      this.router.route('/:accountName/:appName/*').get(function(req, res, next) {
        var accountName, appName, gallery, promise;
        accountName = req.params.accountName;
        appName = req.params.appName;
        gallery = new Gallery(accountName);
        promise = gallery.downloadFilesFromApp(appName).then(function() {
          var appPath, application;
          console.log('asdasd');
          appPath = '../apps/colossus';
          application = require(appPath);
          return application.run(accountName, appName, req, res, next);
        });
        return promise["catch"](function(err) {
          return next(err);
        });
      });
    }

    return AppRouter;

  })();

  module.exports = function(router) {
    return new AppRouter(router);
  };

}).call(this);

//# sourceMappingURL=app-router.map
