// Generated by CoffeeScript 1.7.1
(function() {
  var AppRouter, Gallery, fresh;

  Gallery = require('./lib/gallery');

  fresh = require('fresh-require');

  AppRouter = (function() {
    function AppRouter(router) {
      this.router = router;
      this.router.route('/:accountName/:appName/*').get(function(req, res, next) {
        var accountName, appName, gallery, promise, sandBox;
        accountName = req.params.accountName;
        appName = req.params.appName;
        sandBox = req.headers['x-vtex-sandbox'];
        gallery = new Gallery(accountName);
        promise = gallery.downloadFilesFromApp(appName, sandBox).then(function(path) {
          var appPath, application;
          appPath = path;
          application = fresh('../' + appPath + 'colossus', require);
          return application.run(accountName, appName, req, res, next);
        });
        return promise["catch"](function(err) {
          return next(err);
        });
      });
    }

    return AppRouter;

  })();

  module.exports = function(router) {
    return new AppRouter(router);
  };

}).call(this);

//# sourceMappingURL=app-router.map
